### ISSUE TITLE
System not sent email order to customer when make a payment via omise 

### ISSUE THREAD

**Issue by A-Kits** [omise/omise-magento#89] opened 2017-08-24 14:16 UTC
I found a issue about email transaction.
When customer make a payment via omise, A email order was not sent to customer.
This issue happen only Omise payment other method such as Paypal, Direct Deposit not have tis issue.
plugin Omise ver 1.12 Magento ver.1.9.3.4 

Thank

**Comment by guzzilar** [comment] 2017-08-25 03:48
@A-Kits Hi

Can you check at your order that has email transaction issue if that order status was set to 'pending' or 'processing'?

**Comment by A-Kits** [comment] 2017-08-25 05:22
Hi
Order status was sent as processing and has a notification " email order
was not sent" on head of order page.

**Comment by guzzilar** [comment] 2017-08-25 05:24
@A-Kits Ok thanks. I'll check on it.

**Comment by A-Kits** [comment] 2017-08-30 09:49
Hi, Do you  have any updates?
Did issue happen with other user ?

**Comment by guzzilar** [comment] 2017-08-30 09:54
@A-Kits Hi,
This ticket is still in progress.
However, so far, I haven't heard this issue from other users.

**Comment by A-Kits** [comment] 2017-08-30 10:36
Hi 
Do you test this plugin with your magento system? 
I concern that this issue happen because omise plugin or because of my magento system.
Anyway for my website  this issue happened with only omise payment.

**Comment by A-Kits** [comment] 2017-11-09 06:49
Do you have any update for this issue?

**Comment by guzzilar** [comment] 2017-11-09 07:15
@A-Kits Hi, I kinda found one spot that may relate to this issue. Working on it now (but I guess Im gonna need a bit more time).

**Comment by bokoko** [comment] 2018-02-26 07:40
im facing the same problem here. My magento version is 2.1.0. The other payment option can send e-mail confirmation order just fine, but the email do not send when user pick omise payment option.

thank you very much

**Comment by guzzilar** [comment] 2018-02-27 06:58
Hi @bokoko thanks for your report.
I'm adding tag `status: Need investigation` here as we are trying to reproduce the issue but still can't figure it out why this problem occurred to you (we've tested and email has been sent properly).

But there has to be something behind.. will let you know once we have any updates❗️ 

By the way, I'm guessing you are using Omise-Magento v2.2 right?

**Comment by Jamjann** [comment] 2018-09-28 04:48
Hi everyone.Now I'm using Magento 1.9. and also face this problems too.Do you have any updates?

**Comment by Jamjann** [comment] 2018-09-28 04:49
Hi everyone.Now I'm using Magento 1.9. and also face this problems.Do you have any updates?

**Comment by keeratita** [comment] 2019-07-24 13:29
I think this issue should be closed due to it was fixed on Omise-Magento version 1.16.

**Closed by keeratita** 2019-07-24 13:29 UTC
Labels: project: 1.x, project: 2.x, status: Need investigation
